
package com.sunyard.module.storage.ecm.service;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;

import org.springframework.stereotype.Component;

import com.sunyard.framework.common.exception.SunyardException;
import com.sunyard.framework.common.result.ResultCode;
import com.sunyard.module.storage.config.properties.SunEcmBusinessWebServiceProperties;
import com.sunyard.module.storage.ecm.webservice.BusinessWebService;

import lombok.extern.slf4j.Slf4j;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035 Generated source version: 2.2
 *
 * @author 刘港
 */
@Slf4j
@Component
public class SunEcmBusinessWebService {

    private static Service service;


    private final SunEcmBusinessWebServiceProperties sunEcmBusinessWebServiceProperties;

    public SunEcmBusinessWebService(SunEcmBusinessWebServiceProperties properties) {
        this.sunEcmBusinessWebServiceProperties = properties;
        String wsdlUrl = sunEcmBusinessWebServiceProperties.getWsdlUrl();
        Boolean enable = sunEcmBusinessWebServiceProperties.getEnable();
        log.debug("SunEcm地址:{}", wsdlUrl);
        log.info("SunEcmBusinessWebService是否连接老影像:{}", enable);
        if (enable){
            if (service == null) {
                URL url = null;
                try {
                    url = new URL(wsdlUrl);
                } catch (MalformedURLException e) {
                    throw new RuntimeException(e);
                }
                // 指定命名空间和服务名称
                QName qName =
                        new QName("http://impl.batch.mgmt.webservice.ecm.insurance.sunyard.com/", "businessWebService");
                try {
                    service = Service.create(url, qName);
                    log.info("影像系统WebService 连接成功");
                } catch (Exception e) {
                    log.error("影像系统WebService 连接失败", e);
                    service = null;
                }
            }
        }
    }

    /**
     * @return Result returns BusinessWebService
     */
    @WebEndpoint(name = "BusinessWebServiceImplPort")
    public BusinessWebService getBusinessWebServiceImplPort() {
        // 通过getPort方法返回指定接口
        if (service == null) {
            throw new SunyardException(ResultCode.SYSTEM_EM_ERROR, "影像系统WebService 连接失败");
        } else {
            return service.getPort(
                    new QName("http://impl.batch.mgmt.webservice.ecm.insurance.sunyard.com/", "BusinessWebServiceImplPort"),
                    BusinessWebService.class);
        }
    }
}
