
package com.sunyard.module.storage.ecm.webservice;


import com.sunyard.module.storage.dto.webservice.BusinessRespBean;
import com.sunyard.module.storage.dto.webservice.ResponseBean;
import com.sunyard.module.storage.ecm.webservice.dto.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035 Generated source version: 2.2
 * 
 * @author 刘港
 */
@WebService(name = "BusinessWebService", targetNamespace = "http://batch.mgmt.webservice.ecm.insurance.sunyard.com/")
@XmlSeeAlso({ObjectFactory.class})
public interface BusinessWebService {

    /**
     * 修改业务信息
     * @param arg0 目标业务
     * @return Result response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modBusiness",
        targetNamespace = "http://batch.mgmt.webservice.ecm.insurance.sunyard.com/", className = "com.ModBusiness")
    @ResponseWrapper(localName = "modBusinessResponse",
        targetNamespace = "http://batch.mgmt.webservice.ecm.insurance.sunyard.com/",
        className = "com.ModBusinessResponse")
    ResponseBean modBusiness(@WebParam(name = "arg0", targetNamespace = "") BusinessRespBean arg0);

    /**
     * 删除业务信息
     * @param arg0 目标业务
     * @return Result returns com.BusinessRespBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delBusiness",
        targetNamespace = "http://batch.mgmt.webservice.ecm.insurance.sunyard.com/", className = "com.DelBusiness")
    @ResponseWrapper(localName = "delBusinessResponse",
        targetNamespace = "http://batch.mgmt.webservice.ecm.insurance.sunyard.com/",
        className = "com.DelBusinessResponse")
    ResponseBean delBusiness(@WebParam(name = "arg0", targetNamespace = "") BusinessRespBean arg0);

    /**
     * 添加业务信息
     * @param arg0 目标业务
     * @return Result returns com.BusinessRespBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addBusiness",
        targetNamespace = "http://batch.mgmt.webservice.ecm.insurance.sunyard.com/", className = "com.AddBusiness")
    @ResponseWrapper(localName = "addBusinessResponse",
        targetNamespace = "http://batch.mgmt.webservice.ecm.insurance.sunyard.com/",
        className = "com.AddBusinessResponse")
    ResponseBean addBusiness(@WebParam(name = "arg0", targetNamespace = "") BusinessRespBean arg0);

}
