--- #################### feign 连接池配置 ####################
feign:
  client:
    config:
      default: # default全局的配置
        connectTimeout: 2000000 # 连接超时时间，单位毫秒
        readTimeout: 2000000    # 读取超时时间，单位毫秒
        loggerLevel: BASIC # 日志级别，BASIC就是基本的请求和响应信息
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 300 # 最大的连接数
    max-connections-per-route: 100 # 每个路径的最大连接数
  compression:
    request:
      enabled: true
    response:
      enabled: true