#公司名称-税号校验静态配置
company-info:
  #是否开启税号和公司名称校验
  doValidate: true
  companyInfoMap:
    HX01:
      code: HX01
      name: 广东华兴玻璃股份有限公司
      taxId: 91440600X18309815H
    HX02:
      code: HX02
      name: 佛山华兴玻璃有限公司
      taxId: 914406007799538243
    HX03:
      code: HX03
      name: 佛山市三水华兴玻璃有限公司
      taxId: 91440607782024663D
    HX04:
      code: HX04
      name: 福建华兴玻璃有限公司
      taxId: 91350305796061529B
    HX05:
      code: HX05
      name: 福建长城华兴玻璃有限公司
      taxId: 913503036808849452
    HX06:
      code: HX06
      name: 大冶市华兴玻璃有限公司
      taxId: 91420281726114023N
    HX07:
      code: HX07
      name: 浙江华兴玻璃有限公司
      taxId: 91330424790994811Y
    HX08:
      code: HX08
      name: 江苏华兴玻璃有限公司
      taxId: 91321391788870617T
    HX09:
      code: HX09
      name: 河南华兴玻璃有限公司
      taxId: 91410100793223975G
    HX10:
      code: HX10
      name: 河北华兴玻璃有限公司
      taxId: 9113102366528882X3
    HX11:
      code: HX11
      name: 新疆华兴玻璃有限公司
      taxId: 916590016606411373
    HX12:
      code: HX12
      name: 湖南华兴玻璃有限公司
      taxId: 91430981576590154R
    HX13:
      code: HX13
      name: 贵州华兴玻璃有限公司
      taxId: 9152042157713533XX
    HX14:
      code: HX14
      name: 哈尔滨华兴玻璃有限公司
      taxId: 91230199MA1B7P4C91
    HX15:
      code: HX15
      name: 重庆华兴玻璃有限公司
      taxId: 91500226MA607K5Q5H

#可用于验真的发票类型代码
can-be-validated-invoice-type-code:
  #增值税专用发票
  - 10100
  #增值税普通发票
  - 10101
  #增值税电子普通发票
  - 10102
  #增值税普通发票(卷票)
  - 10103
  #机动车销售统一发票
  - 10104
  #二手车销售统一发票
  - 10105

#可用于校验税号和公司名称的发票种类代码
can-be-validated-company-info-invoice-type-code:
  #增值税专用发票
  - 10100
  #增值税普通发票
  - 10101
  #增值税电子普通发票
  - 10102
  #增值税普通发票(卷票)
  - 10103
  #机动车销售统一发票
  - 10104
  #二手车销售统一发票
  - 10105
  #机打发票
  - 10400
  #完税证明
  - 10902

#可用于校验大小发票号和发票代码的的发票种类代码
can-be-confirmed-invoice-type-code:
  #增值税专用发票
  - 10100
  #增值税普通发票
  - 10101
  #增值税电子普通发票
  - 10102
  #增值税普通发票(卷票)
  - 10103

#用于匹配发票类型和税前金额对应字段名称(Glority的字段定义太坑爹)
type-code-pretax-amount-key-name:
  #增值税专用发票
  10100: pretax_amount
  #机动车销售统一发票
  10101: pretax_amount
  #二手车销售统一发票
  10102: total

validate-result-code-des:
  10000: 查验成功
  10001: 查无此票
  10002: 查验信息不一致
  10003: 该票当天验真次数超过限制
  10004: 不支持验真发票类型
  10005: 无效参数
  10006: 其它错误

#用于匹配发票配型代码和发票名称
invoice-type-code-name:
  10100: 增值税专用发票
  10101: 增值税普通发票
  10102: 增值税电子普通发票
  10103: 增值税普通发票(卷票)
  10104: 机动车销售统一发票
  10105: 二手车销售统一发票
  10505a: 船票
  10200: 定额发票
  10400: 机打发票
  10500: 出租车发票
  10503: 火车票
  10505: 客运汽车
  10506: 航空运输电子客票行程单
  10507: 过路费发票
  #  //10900是个坑,只要是图片,没有被识别为其他几种有效的发票类型,都会默认归类为10090(其他可报销发票)
  10900: 无法识别的图片
  20100: 国际小票
  20105: 滴滴出行行程单
  10902: 完税证明
